version: '3.3'

services:
    # Development related
    db:
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile
            args:
                # These values should be in sync with environment
                # for development. If you change them, you'll 
                # need to rebuild the container
                - POSTGRES_DB=locations
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=somepassword
                - POSTGRES_PORT=5432

    test:
        env_file: environment.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build: 
            context: .
        entrypoint: pytest -c tests/pytest.ini
        depends_on:
            - db
        volumes:
            - ./src:/opt/code
            - ./tests:/opt/code/tests

    # Producion related
    server:
        env_file: environment.env
        image: locations_server
        build: 
            context: .
        command: /opt/server/start_server.sh
        ports:
            - "8080:80"
        depends_on:
            - db
