version: '3.3'

services:
    # Development related
    test:
        build: 
            context: .
        entrypoint: pytest
        volumes:
            - ./src:/opt/code
            - ./tests:/opt/code/

    # Producion related
    server:
        image: locations_server
        build: 
            context: .
        command: /opt/server/start_server.sh
        ports:
            - "8080:80"
        deploy:
          endpoint_mode: dnsrr
          resources:
            limits:
              memory: 16M
            reservations:
              memory: 16M
